In [5]:
import numpy as np
import time
import math
from pprint import pprint

np.random.seed(42)

empty_2x2 = np.empty((2, 2))
print("Here is an empty 2x2 array:\n", empty_2x2, "\n")

ones_4x2 = np.ones((4, 2))
print("This is a 4x2 array full of ones:\n", ones_4x2, "\n")

filled_3x3_with_7 = np.full((3, 3), fill_value=7, dtype=int)
print("A 3x3 matrix filled with the number 7:\n", filled_3x3_with_7, "\n")

sample = np.array([[1.5, 2.5], [3.5, 4.5]])
zeros_like_sample = np.zeros_like(sample)
print("A zeros matrix shaped like 'sample':\n", zeros_like_sample, "\n")

ones_like_sample = np.ones_like(sample)
print("An all-ones matrix shaped like 'sample':\n", ones_like_sample, "\n")

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("Converted Python list to NumPy array:", array_from_list, "\n")

arr_10_49 = np.arange(10, 50)
print("Numbers from 10 to 49:", arr_10_49, "\n")

matrix_3x3_0_8 = np.arange(9).reshape((3, 3))
print("3x3 matrix with values from 0 to 8:\n", matrix_3x3_0_8, "\n")

identity_3x3 = np.eye(3, dtype=int)
print("Identity matrix of size 3x3:\n", identity_3x3, "\n")

rand_30 = np.random.random(30)
mean_rand_30 = rand_30.mean()
print("Mean of 30 random numbers:", mean_rand_30, "\n")

rand_10x10 = np.random.random((10, 10))
min_val = rand_10x10.min()
max_val = rand_10x10.max()
print("In a 10x10 random matrix → min:", min_val, "max:", max_val, "\n")

zeros_10 = np.zeros(10, dtype=int)
zeros_10[4] = 1
print("Zero array with the 5th element set to 1:", zeros_10, "\n")

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("Original array:", arr)
print("Reversed array:", reversed_arr, "\n")

n = 5
border = np.ones((n, n), dtype=int)
border[1:-1, 1:-1] = 0
print("5x5 array with a border of ones:\n", border, "\n")

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard pattern (8x8):\n", checkerboard, "\n")

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x + y =\n", x + y, "\n")
print("x - y =\n", x - y, "\n")
print("x multiplied by 3 =\n", x * 3, "\n")
print("x squared =\n", x ** 2, "\n")

print("Dot product v · w =", np.dot(v, w))
print("Dot product x · v =", np.dot(x, v))
print("Matrix dot x · y =\n", np.dot(x, y), "\n")

print("x and y stacked vertically:\n", np.concatenate((x, y), axis=0), "\n")
print("v and w stacked as columns:\n", np.column_stack((v, w)), "\n")

try:
    concat_x_v = np.concatenate((x, v), axis=0)
except Exception as e:
    concat_x_v = f"Error: {e}"
print("Trying to combine x and v gives:", concat_x_v, "\n")

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_from_A = np.dot(A, A_inv)
print("A multiplied by its inverse (should be identity):\n", identity_from_A, "\n")

print("Rounded identity matrix:\n", np.round(identity_from_A, 10), "\n")

AB = np.dot(A, B)
BA = np.dot(B, A)
print("A * B =\n", AB)
print("B * A =\n", BA)
print("Are A*B and B*A equal? →", np.allclose(AB, BA), "\n")

left = np.dot(A, B).T
right = np.dot(B.T, A.T)
print("Transpose of (A·B):\n", left)
print("Bᵀ multiplied by Aᵀ:\n", right)
print("Do they match?", np.allclose(left, right), "\n")

A_sys = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]], dtype=float)
B_sys = np.array([-1, -3, 9], dtype=float)

X_solution = np.linalg.solve(A_sys, B_sys)
print("Solution of the system (x, y, z):", X_solution, "\n")

A_sys_inv = np.linalg.inv(A_sys)
print("Solution using inverse method:", A_sys_inv.dot(B_sys), "\n")

def measure_time(func, *args, repeats=1, **kwargs):
    start = time.perf_counter()
    for _ in range(repeats):
        result = func(*args, **kwargs)
    end = time.perf_counter()
    return end - start, result

n = 1_000_000
list_a = list(range(n))
list_b = list(range(n, 2*n))

def list_elementwise_add(a, b):
    return [x + y for x, y in zip(a, b)]

np_a = np.array(list_a)
np_b = np.array(list_b)

t_list_add, _ = measure_time(list_elementwise_add, list_a, list_b)
t_np_add, _ = measure_time(np.add, np_a, np_b)

print(f"Adding 1 million elements → Python lists: {t_list_add:.4f}s, NumPy: {t_np_add:.4f}s")

def list_elementwise_mul(a, b):
    return [x * y for x, y in zip(a, b)]

t_list_mul, _ = measure_time(list_elementwise_mul, list_a, list_b)
t_np_mul, _ = measure_time(np.multiply, np_a, np_b)

print(f"Multiplying 1 million elements → Python lists: {t_list_mul:.4f}s, NumPy: {t_np_mul:.4f}s")

def list_dot(a, b):
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

t_list_dot, dot_list_result = measure_time(list_dot, list_a, list_b)
t_np_dot, dot_np_result = measure_time(np.dot, np_a, np_b)

print(f"Dot product (1M size) → Python lists: {t_list_dot:.4f}s, NumPy: {t_np_dot:.4f}s")
print("Are the dot product results equal?", dot_list_result == dot_np_result, "\n")

def generate_python_matrix(rows, cols, seed=0):
    rng = np.random.RandomState(seed)
    return rng.random((rows, cols)).tolist()

def python_matrix_multiply(A, B):
    m = len(A)
    p = len(A[0])
    n = len(B[0])
    C = [[0.0] * n for _ in range(m)]
    for i in range(m):
        for k in range(p):
            for j in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

M = 200
print(f"Testing matrix multiplication for size {M}x{M}")

np_mat1 = np.random.random((M, M))
np_mat2 = np.random.random((M, M))

py_mat1 = np_mat1.tolist()
py_mat2 = np_mat2.tolist()

t_python_matmul, _ = measure_time(python_matrix_multiply, py_mat1, py_mat2)
t_numpy_matmul, _ = measure_time(np.matmul, np_mat1, np_mat2)

print(f"Matrix multiply {M}x{M} → Python lists: {t_python_matmul:.4f}s, NumPy: {t_numpy_matmul:.4f}s")


Here is an empty 2x2 array:
 [[23. 51.]
 [13. 29.]] 

This is a 4x2 array full of ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 

A 3x3 matrix filled with the number 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]] 

A zeros matrix shaped like 'sample':
 [[0. 0.]
 [0. 0.]] 

An all-ones matrix shaped like 'sample':
 [[1. 1.]
 [1. 1.]] 

Converted Python list to NumPy array: [1 2 3 4] 

Numbers from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49] 

3x3 matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 

Identity matrix of size 3x3:
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 

Mean of 30 random numbers: 0.43859727209743676 

In a 10x10 random matrix → min: 0.005522117123602399 max: 0.9868869366005173 

Zero array with the 5th element set to 1: [0 0 0 0 1 0 0 0 0 0] 

Original array: [1 2 0 0 4 0]
Reversed array: [0 4 0 0 2 1] 

5x5 array with a border of ones:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]